source :rubygems

gem 'police-tracking', '>= 0.0.0', path: '../police-tracking'

group :development do
  gem 'minitest', '>= 2.11.2'
  gem 'yard', '>= 0.7'
  gem 'rdoc', '>= 3.12'
  gem 'bundler', '>= 1.0.0'
  gem 'jeweler', '>= 1.8.3'
  gem 'simplecov', '>= 0.6.1'
end
