source :rubygems

gem 'police-dataflow', '>= 0.0.0', path: '../police-dataflow'
gem 'police-labels', '>= 0.0.0', path: '../police-labels'
gem 'rack', '>= 1.4.1'

group :development do
  gem 'bundler', '>= 1.1.0'
  gem 'jeweler', '>= 1.8.3'
  gem 'minitest', '>= 2.11.2'
  gem 'rack-test', '>= 0.6.1'
  gem 'rdoc', '>= 3.12'
  gem 'simplecov', '>= 0.6.1'
  gem 'yard', '>= 0.7'
end
