# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "police-vminfo"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Victor Costan"]
  s.date = "2013-05-08"
  s.description = "Collects information about the Ruby VM implementation details."
  s.email = "victor@costan.us"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/police-vminfo.rb",
    "lib/police/vminfo.rb",
    "lib/police/vminfo/objects.rb",
    "lib/police/vminfo/paths.rb",
    "lib/police/vminfo/signature.rb",
    "police-vminfo.gemspec",
    "test/helper.rb",
    "test/vminfo/objects_test.rb",
    "test/vminfo/paths_test.rb",
    "test/vminfo/signature_test.rb"
  ]
  s.homepage = "http://github.com/pwnall/police-vminfo"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Information about the Ruby VM internals."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

