source :rubygems

gem 'police-vminfo', '>= 0.0.2', path: '../police-vminfo'

group :development do
  gem 'bundler', '>= 1.1.0'
  gem 'jeweler', '>= 1.8.3'
  gem 'minitest', '>= 2.11.2'
  gem 'rdoc', '>= 3.12'
  gem 'simplecov', '>= 0.6.1'
  gem 'yard', '>= 0.7'
end
